from sqlalchemy import Boolean, Column, Integer, FLOAT,String, DateTime, BigInteger, ForeignKey,DATE,DATETIME
from sqlalchemy.orm import relationship
from pydantic import BaseModel
from db import Base
from db import ENGINE

import datetime

class PatientGeneralTable(Base):
  __tablename__='patient_general'
  p_id = Column(Integer, primary_key=True, autoincrement=True)
  birth_date = Column(Integer,nullable=False)
  sex=Column(Integer,nullable=False,)
  p_name=Column(String(50),nullable=False)
  emp_id=Column(Integer,nullable=False)
  admin_date=Column(DATE, nullable=False)
  disch_date=Column(DATE,nullable=True)

  vital_record_all = relationship("VitalRecordAll", back_populates="patient_general")


class VitalRecordAll(Base):
  __tablename__ = 'vital_record_all'
  record_id = Column(Integer, primary_key=True, autoincrement=True)
  p_id=Column(Integer,ForeignKey('patient_general.p_id'))
  birth_date=Column(Integer,nullable=False)
  input_time=Column(DATETIME,nullable=False)
  p_age=Column(Integer,nullable=False)
  hr=Column(Integer,nullable=False)
  p_temp=Column(FLOAT,nullable=False)
  resp=Column(Integer,nullable=False)
  sbp=Column(Integer,nullable=False)
  dbp=Column(Integer,nullable=False)
  BaseExcess=Column(FLOAT,nullable=True,default=None)
  HCO3=Column(FLOAT,nullable=True,default=None)
  FiO2=Column(FLOAT,nullable=True,default=None)
  pH=Column(FLOAT,nullable=True,default=None)
  PaCO2=Column(FLOAT,nullable=True,default=None)
  SaO2=Column(FLOAT,nullable=True,default=None)
  Alkalinephos=Column(FLOAT,nullable=True,default=None)
  Calcium=Column(FLOAT,nullable=True,default=None)
  Chloride=Column(FLOAT,nullable=True,default=None)
  Creatinine=Column(FLOAT,nullable=True,default=None)
  Bilirubin_direct=Column(FLOAT,nullable=True,default=None)
  Glucose=Column(FLOAT,nullable=True,default=None)
  Lactate=Column(FLOAT,nullable=True,default=None)
  Phosphate=Column(FLOAT,nullable=True,default=None)
  Potassium=Column(FLOAT,nullable=True,default=None)
  Bilirubin_total=Column(FLOAT,nullable=True,default=None)
  TroponinI=Column(FLOAT,nullable=True,default=None)
  Hct=Column(FLOAT,nullable=True,default=None)
  Hgb=Column(FLOAT,nullable=True,default=None)
  PTT=Column(FLOAT,nullable=True,default=None)
  WBC=Column(FLOAT,nullable=True,default=None)
  Fibrinogen=Column(FLOAT,nullable=True,default=None)
  Platelets=Column(FLOAT,nullable=True,default=None)
  sepsis_in_six=Column(Integer,nullable=True,default=None)
  sepsis_percent=Column(FLOAT,nullable=True,default=None)
  
  patient_general = relationship("PatientGeneralTable", back_populates="vital_record_all")


class VitalRecordNowView(Base):
  __tablename__='vital_record_now_view'
  pid = Column(Integer)
  birth_date = Column(Integer,nullable=False)
  sex=Column(Integer,nullable=False,)
  p_name=Column(String(50),nullable=False)
  emp_id=Column(Integer,nullable=False)
  admin_date=Column(DATE, nullable=False)
  disch_date=Column(DATE,nullable=True)
  record_id = Column(Integer, primary_key=True, autoincrement=True)
  birth_date=Column(Integer,nullable=False)
  input_time=Column(DATETIME,nullable=False)
  age=Column(Integer,nullable=False)
  hr=Column(Integer,nullable=False)
  p_temp=Column(FLOAT,nullable=False)
  resp=Column(Integer,nullable=False)
  sbp=Column(Integer,nullable=False)
  dbp=Column(Integer,nullable=False)
  BaseExcess=Column(FLOAT,nullable=True,default=None)
  HCO3=Column(FLOAT,nullable=True,default=None)
  FiO2=Column(FLOAT,nullable=True,default=None)
  pH=Column(FLOAT,nullable=True,default=None)
  PaCO2=Column(FLOAT,nullable=True,default=None)
  SaO2=Column(FLOAT,nullable=True,default=None)
  Alkalinephos=Column(FLOAT,nullable=True,default=None)
  Calcium=Column(FLOAT,nullable=True,default=None)
  Chloride=Column(FLOAT,nullable=True,default=None)
  Creatinine=Column(FLOAT,nullable=True,default=None)
  Bilirubin_direct=Column(FLOAT,nullable=True,default=None)
  Glucose=Column(FLOAT,nullable=True,default=None)
  Lactate=Column(FLOAT,nullable=True,default=None)
  Phosphate=Column(FLOAT,nullable=True,default=None)
  Potassium=Column(FLOAT,nullable=True,default=None)
  Bilirubin_total=Column(FLOAT,nullable=True,default=None)
  TroponinI=Column(FLOAT,nullable=True,default=None)
  Hct=Column(FLOAT,nullable=True,default=None)
  Hgb=Column(FLOAT,nullable=True,default=None)
  PTT=Column(FLOAT,nullable=True,default=None)
  WBC=Column(FLOAT,nullable=True,default=None)
  Fibrinogen=Column(FLOAT,nullable=True,default=None)
  Platelets=Column(FLOAT,nullable=True,default=None)
  sepsis_in_six=Column(Integer,nullable=True,default=None)
  sepsis_percent=Column(FLOAT,nullable=True,default=None)

# 모든 환자의 최근 데이터 view
class VitalRecordLatestView(Base):
  __tablename__='vital_record_latest_view'
  pid = Column(Integer)
  birth_date = Column(Integer,nullable=False)
  sex=Column(Integer,nullable=False,)
  p_name=Column(String(50),nullable=False)
  emp_id=Column(Integer,nullable=False)
  admin_date=Column(DATE, nullable=False)
  disch_date=Column(DATE,nullable=True)
  record_id = Column(Integer, primary_key=True, autoincrement=True)
  birth_date=Column(Integer,nullable=False)
  input_time=Column(DATETIME,nullable=False)
  age=Column(Integer,nullable=False)
  hr=Column(Integer,nullable=False)
  temp=Column(FLOAT,nullable=False)
  resp=Column(Integer,nullable=False)
  sbp=Column(Integer,nullable=False)
  dbp=Column(Integer,nullable=False)
  BaseExcess=Column(FLOAT,nullable=True,default=None)
  HCO3=Column(FLOAT,nullable=True,default=None)
  FiO2=Column(FLOAT,nullable=True,default=None)
  pH=Column(FLOAT,nullable=True,default=None)
  PaCO2=Column(FLOAT,nullable=True,default=None)
  SaO2=Column(FLOAT,nullable=True,default=None)
  Alkalinephos=Column(FLOAT,nullable=True,default=None)
  Calcium=Column(FLOAT,nullable=True,default=None)
  Chloride=Column(FLOAT,nullable=True,default=None)
  Creatinine=Column(FLOAT,nullable=True,default=None)
  Bilirubin_direct=Column(FLOAT,nullable=True,default=None)
  Glucose=Column(FLOAT,nullable=True,default=None)
  Lactate=Column(FLOAT,nullable=True,default=None)
  Phosphate=Column(FLOAT,nullable=True,default=None)
  Potassium=Column(FLOAT,nullable=True,default=None)
  Bilirubin_total=Column(FLOAT,nullable=True,default=None)
  TroponinI=Column(FLOAT,nullable=True,default=None)
  Hct=Column(FLOAT,nullable=True,default=None)
  Hgb=Column(FLOAT,nullable=True,default=None)
  PTT=Column(FLOAT,nullable=True,default=None)
  WBC=Column(FLOAT,nullable=True,default=None)
  Fibrinogen=Column(FLOAT,nullable=True,default=None)
  Platelets=Column(FLOAT,nullable=True,default=None)
  sepsis_in_six=Column(Integer,nullable=True,default=None)
  sepsis_percent=Column(FLOAT,nullable=True,default=None)